### ISSUE TITLE
Withdraw and Bank commands are using the same time limit

### ISSUE THREAD

**Issue by TCHE614** [Weaselcore/Bear_Bot#5]
I can reproduce this bug as seen in the screenshot
![image](https://user-images.githubusercontent.com/48304096/113106437-44dfd400-925f-11eb-9ec2-0042291d7cca.png)

This is a critical issue as if you want to withdraw and steal then bank the combo is not possible please look into it

**Comment by Weaselcore** [comment]
Fixed in the beta branch will pull after blackjack feature releases.
